Duil-App/Duil-App/Controllers/API/EncomendasController.cs
using Duil_App.Data;
using Duil_App.Models;
using Duil_App.Models.ViewModels;
using Humanizer;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace Duil_App.Controllers.API
{

    [Route("api/[controller]")]
    [ApiController]
    public class EncomendasController : ControllerBase
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<Utilizadores> _userManager;

        public EncomendasController(ApplicationDbContext context, UserManager<Utilizadores> userManager)
        {
            _context = context;
            _userManager = userManager;
        }


        // GET: api/<EncomendasController>
        /// <summary>
        /// Devolve uma lista com todas as Encomendas
        /// </summary>
        /// <returns></returns>
        [HttpGet]
        public async Task<ActionResult<IEnumerable<Encomendas>>> GetEncomendas()
        {
            return await _context.Encomendas.ToListAsync();
        }

        // GET api/<EncomendasController>/5
        /// <summary>
        /// Obtem uma Encomenda especifica
        /// </summary>
        /// <param name="id">identificador da Encomenda</param>
        /// <returns>Encomenda com o ID passado</returns>
        [HttpGet("{id}")]
        public async Task<ActionResult<Encomendas>> GetEncomenda(int id)
        {
            var encomenda = await _context.Encomendas.FindAsync(id);

            if (encomenda == null)
            {
                return NotFound();
            }

            return encomenda;
        }


        // POST api/<EncomendasController>
        /// <summary>
        /// Adiciona uma encomenda
        /// </summary>
        /// <param name="dto"></param>
        /// <returns></returns>
        [HttpPost]
        public async Task<ActionResult<Encomendas>> PostEncomenda(EncomendaDTO dto)
        {
            var cliente = await _context.Clientes.FirstOrDefaultAsync(c => c.Nif == dto.ClienteId);

            var novaEncomenda = new Encomendas
            {
                IdLadoCliente   = dto.IdLadoCliente,
                ClienteId       = dto.ClienteId,
                Cliente         = cliente ?? throw new ArgumentNullException(nameof(cliente), "Cliente não encontrado."),
                Data            = DateTime.Today,
                Estado          = Estados.Pendente,
                TotalPrecoUnit  = 1,                    //Duvida aqui.
                QuantidadeTotal = 1,                   // e aqui
                Transportadora  = string.Empty
            };


            _context.Encomendas.Add(novaEncomenda);
            await _context.SaveChangesAsync();

            return CreatedAtAction(nameof(GetEncomenda),
                       new { id = novaEncomenda.Id },
                       novaEncomenda);
        }


        // GET: api/Encomendas/minhasEncomendas
        /// <summary>
        /// Devolve uma lista com todas as Encomendas do cliente autenticado
        /// </summary>
        [HttpGet("minhasEncomendas")]
        [Authorize(Roles = "Cliente")]
        public async Task<ActionResult<IEnumerable<Encomendas>>> VerMinhas()
        {
            var userNif = _userManager.Users
                .Where(u => u.Id == _userManager.GetUserId(User))
                .Select(u => u.NIF)
                .FirstOrDefault();
            
            return await _context.Encomendas
                .Where(e => e.ClienteId == userNif)
                .ToListAsync();
        }

        // POST: api/Encomendas/cliente
        /// <summary>
        /// Cria a encomenda do cliente autenticado
        /// </summary>
        /// <param name="dto"></param>
        [HttpPost("cliente")]
        [Authorize(Roles = "Cliente")]
        public async Task<ActionResult<Encomendas>> CriarEncomendaCliente([FromBody] EncomendaClienteDTO dto)
        {
            var userNif = _userManager.Users
               .Where(u => u.Id == _userManager.GetUserId(User))
               .Select(u => u.NIF)
               .FirstOrDefault();

            var novaEncomenda = new Encomendas
            {
                IdLadoCliente = dto.IdLadoCliente,
                //Como é autenticado, existe
                ClienteId = userNif!,
                Cliente = _context.Clientes.FirstOrDefault(e => e.Nif == userNif)!,
                Data = DateTime.Today,
                Estado = Estados.Pendente,
                TotalPrecoUnit = 1,                    //Duvida aqui.
                QuantidadeTotal = 1,                   // e aqui
                Transportadora = dto.Transportadora
            };

            _context.Encomendas.Add(novaEncomenda);
            await _context.SaveChangesAsync();

            return CreatedAtAction(nameof(VerMinhas), new { id = novaEncomenda.Id }, novaEncomenda);
        }


        // PUT api/<EncomendasController>/5
        /// <summary>
        /// Modifica uma encomenda
        /// </summary>
        /// <param name="id"></param>
        /// <param name="dto"></param>
        [HttpPut("{id}")]
        public async Task<IActionResult> PutEncomenda(int id, EncomendaDTO dto)
        {
            var encomenda = await _context.Encomendas.FindAsync(id);
           
            if (encomenda == null)
            {
                return BadRequest();
            }

            // Atualizar apenas os campos permitidos
            encomenda.ClienteId = dto.ClienteId;
            encomenda.Transportadora = dto.Transportadora;
            encomenda.IdLadoCliente = dto.IdLadoCliente;

            _context.Entry(encomenda).State = EntityState.Modified;
            try
            {
                await _context.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                return StatusCode(500, "Erro de concorrência ao atualizar a encomenda.");
            }

            return NoContent();
        }

        // DELETE api/<EncomendasController>/5
        /// <summary>
        /// Apaga uma encomenda
        /// </summary>
        /// <param name="id"></param>
        [HttpDelete("{id}")]
        public async Task<IActionResult> DeleteEncomenda(int id)
        {
            var encomenda = await _context.Encomendas.FindAsync(id);
            if (encomenda == null)
            {
                return NotFound();
            }

            _context.Encomendas.Remove(encomenda);
            await _context.SaveChangesAsync();

            return NoContent();
        }
    }

}

Duil-App/Duil-App/Controllers/EncomendasController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Duil_App.Data;
using Duil_App.Models;
using System.Globalization;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Duil_App.Services;
using Microsoft.AspNetCore.SignalR;
using Microsoft.Extensions.Hosting.Internal;
using Duil_App.Code;
using Duil_App.Resources;

namespace Duil_App.Controllers
{

    public class EncomendasController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<Utilizadores> _userManager;
        private readonly IHubContext<RealTimeHub> _hubcontext;

        public EncomendasController(
                ApplicationDbContext context,
                UserManager<Utilizadores> userManager,
                IHubContext<RealTimeHub> hubContext
            )
        {
            _context = context;
            _userManager = userManager;
            _hubcontext = hubContext;
        }

        // Listagem de encomendas
        public async Task<IActionResult> Index(String texto, int? pageNumber)
        {
            if (User.IsInRole("Cliente"))
            {
                await GetClientesEncomendas();
            }

            if (_context.Encomendas == null)
            {
                return Problem("Encomendas é um valor null.");
            }

            // Incluir informação dos clientes
            var encomendas = _context.Encomendas
              .Include(e => e.Cliente)
              .AsQueryable();

            // Aplicar filtro se houver texto de pesquisa
            if (!String.IsNullOrEmpty(texto))
            {
                encomendas = encomendas.Where(t =>
                    t.Cliente.Nome.ToUpper().Contains(texto.ToUpper()));
            }

            // Paginação com 10 resultados
            var pageSize = 10;
            return View(await PaginatedList<Encomendas>.CreateAsync(encomendas.AsNoTracking(), pageNumber ?? 1, pageSize));
        }

        // Detalhes de uma encomenda especifico
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null) return NotFound();

            var encomendas = await _context.Encomendas
                .Include(e => e.Cliente)
                .FirstOrDefaultAsync(m => m.Id == id);

			ViewBag.estadoEncomenda = EstadosTraduzidosHelper.GetUmEstadoTraduzido(encomendas.Estado.ToString());

			return encomendas == null ? NotFound() : View(encomendas);
        }

        /// <summary>
        /// GET CREATE: Encomendas
        /// </summary>
        /// <returns></returns>
        public IActionResult Create()
        {
            if (User.IsInRole("Cliente"))
            {
                var userId = _userManager.GetUserId(User);
                var user = _userManager.GetUserAsync(User).Result;
                var userIdentificador = user.NIF;

                if (userId == null)
                {
                    return RedirectToAction("Login", "Account");
                }
                ViewBag.ClienteId = userIdentificador;
            }

            return View();
        }

        /// <summary>
        /// Post CREATE:  Encomendas
        /// </summary>
        /// <param name="encomenda"></param>
        /// <param name="pecasSelecionadas"></param>
        /// <param name="quantidades"></param>
        /// <returns></returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(
            [Bind("Id,IdLadoCliente,Data,Transportadora,Estado,ClienteId,TotalPrecoUnit,QuantidadeTotal")] Encomendas encomenda,
            List<int> pecasSelecionadas,
            List<int> quantidades)
        {
            if (User.IsInRole("Cliente"))
            {
                encomenda.Estado = Estados.Pendente;
            }

            if (quantidades == null || pecasSelecionadas.Count == 0)
            {
                ModelState.AddModelError("", "Selecione pelo menos uma peça");
            }
            else
            {
                try
                {
                    List<Pecas> pecas = new();

                    // Se for CLiente apenas pode criar encomendas com as suas Pecas
                    if (User.IsInRole("Cliente")) 
                    {

                        var userId = _userManager.GetUserId(User);
                        var user = await _userManager.GetUserAsync(User);
                        var nif = user.NIF;

                        pecas = await _context.Pecas
                            .Where(p => p.ClienteId == nif && pecasSelecionadas.Contains(p.Id))
                            .ToListAsync();
                    }
                    else if (User.IsInRole("Funcionario") || User.IsInRole("Admin")) // Se for Funcionario ou Admin pode criar encomendas com Pecas associadas ao cliente colocado
                    {
                        pecas = await _context.Pecas
                            .Where(p => pecasSelecionadas.Contains(p.Id))
                            .ToListAsync();
                    }

                    if (pecas.Count == 0)
                    {
                        ModelState.AddModelError("", "Não foram encontradas peças válidas para a encomenda.");
                        return View(encomenda);
                    }

                }
                catch
                {
                    ModelState.AddModelError("", "Erro no cálculo dos valores");
                }
            }

            // Validação server side
            if (encomenda.TotalPrecoUnit < 0.01m)
            {
                ModelState.AddModelError("TotalPrecoUnit", "O valor total deve ser maior que zero");
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Add(encomenda);
                    await _context.SaveChangesAsync();

                    if (pecasSelecionadas != null && quantidades != null)
                    {
                        for (int i = 0; i < pecasSelecionadas.Count; i++)
                        {
                            var linha = new LinhaEncomenda
                            {
                                EncomendaId = encomenda.Id,
                                PecaId = pecasSelecionadas[i],
                                Quantidade = quantidades[i]
                            };
                            _context.LinhasEncomendas.Add(linha);
                        }
                        await _context.SaveChangesAsync();
                    }
                    TempData["SuccessMessage"] = "Encomenda criada com sucesso!";

                    // Obter dados da encomenda quando criada
                    var cliente = await _context.Clientes.FindAsync(encomenda.ClienteId);
                    var nomeCliente = cliente.Nome ?? "Cliente Desconhecido";

                    // Notificar os Funcionarios com o Signal R
                    await _hubcontext.Clients.Group("Funcionarios").SendAsync("ReceberNotificacao", new
                    {
                        idEncomenda = encomenda.Id,
                        nomeCliente,
                        data = encomenda.Data.ToString("dd/MM/yyyy"),
                        precoTotal = encomenda.TotalPrecoUnit,
                        quantidadeTotal = encomenda.QuantidadeTotal
                    });

                    return RedirectToAction(nameof(Index));
                }
                catch (Exception ex)
                {
                    ModelState.AddModelError("", $"Error: {ex.Message}");
                }
            }
            else
            {
                // Adicionado error para debuging
                var errors = ModelState.Values.SelectMany(v => v.Errors);
                foreach (var error in errors)
                {
                    Console.WriteLine($"Validation Error: {error.ErrorMessage}");
                }
            }

            return View(encomenda);
        }

        // Formulário de edição de uma encomenda
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null) return NotFound();

            var encomenda = await _context.Encomendas
                .Include(e => e.Cliente)
                .Include(e => e.LinhasEncomenda)
                .ThenInclude(le => le.Peca)
                .FirstOrDefaultAsync(e => e.Id == id);

            if (encomenda == null) return NotFound();

            ViewData["Estado"] = EstadosTraduzidosHelper.GetEstadosTraduzidos();
            return View(encomenda);
        }

        // Submissão do formulario de edição
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id,
        [Bind("Id,IdLadoCliente,Data,Transportadora,Estado,ClienteId,TotalPrecoUnit,QuantidadeTotal")] Encomendas encomenda,
        // Lista de ids das peças
        List<int> pecasSelecionadas,
        List<int> quantidades)
        {
            if (id != encomenda.Id) return NotFound();

            if (pecasSelecionadas != null && quantidades != null)
            {
                // Recalculate totals
                var pecas = await _context.Pecas
                    .Where(p => pecasSelecionadas.Contains(p.Id))
                    .ToListAsync();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(encomenda);

                    var existingLines = await _context.LinhasEncomendas
                        .Where(le => le.EncomendaId == id)
                        .ToListAsync();
                    _context.LinhasEncomendas.RemoveRange(existingLines);

                    if (pecasSelecionadas != null && quantidades != null)
                    {

Duil-App/Duil-App/Views/Encomendas/Delete.cshtml
@model Duil_App.Models.Encomendas
@using Duil_App.Resources

@{
	ViewData["Title"] = Resource.Remover + " " + Resource.EncomendaTexto;
	var estadoEncomenda = ViewBag.estadoEncomenda;
}

<div>
    <a asp-action="Index"><i class="bi bi-arrow-left fs-3 ms-3" title=@Resource.voltarTexto style="color:#6B97AC"></i></a>
</div>

<div class="w-50" style="margin-left:10%; margin-top:5%">
<h3>@Resource.TemACertezaQueDesejaApagarEncomenda</h3>
<div>
		<hr class="mb-5" />
		<dl class="row mt-4">
			<dt class="col-sm-4 mb-3">
				@Html.DisplayNameFor(model => model.Id)
			</dt>
			<dd class="col-sm-5 mb-3">
				@Html.DisplayFor(model => model.Id)
			</dd>
			<dt class="col-sm-4 mb-3">
				@Html.DisplayNameFor(model => model.IdLadoCliente)
			</dt>
			<dd class="col-sm-5 mb-3">
				@Html.DisplayFor(model => model.IdLadoCliente)
			</dd>
			<dt class="col-sm-4 mb-3">
				@Html.DisplayNameFor(model => model.ClienteId)
			</dt>
			<dd class="col-sm-5 mb-3">
				@Html.DisplayFor(model => model.Cliente.Nome)
			</dd>
			<dt class="col-sm-4 mb-3">
				@Html.DisplayNameFor(model => model.Data)
			</dt>
			<dd class="col-sm-5 mb-3">
				@Html.DisplayFor(model => model.Data)
			</dd>
			<dt class="col-sm-4 mb-3">
				@Html.DisplayNameFor(model => model.QuantidadeTotal)
			</dt>
			<dd class="col-sm-5 mb-3">
				@Html.DisplayFor(model => model.QuantidadeTotal)
			<dt class="col-sm-4 mb-3">
					@Html.DisplayNameFor(model => model.TotalPrecoUnit)
			</dt>
			<dd class="col-sm-5 mb-3">
					@Html.DisplayFor(model => model.TotalPrecoUnit)
			</dd>
			<dt class="col-sm-4 mb-3">
					@Html.DisplayNameFor(model => model.Transportadora)
			</dt>
			<dd class="col-sm-5 mb-3">
					@Html.DisplayFor(model => model.Transportadora)
			</dd>
			<dt class="col-sm-4 mb-3">
					@Html.DisplayNameFor(model => model.Estado)
			</dt>
			<dd class="col-sm-5 mb-3">
					@estadoEncomenda
			</dd>
		</dl>
	</div>

    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value=@Resource.Remover class="btn btn-danger" />
    </form>
</div>

Duil-App/Duil-App/Views/Encomendas/Details.cshtml
@model Duil_App.Models.Encomendas
@using Duil_App.Resources

@{
	ViewData["Title"] = Resource.detalhesEncomendaViewTitle;
	var estadosEncomenda = ViewBag.estadoEncomenda;
}


<div>
	<a asp-action="Index"><i class="bi bi-arrow-left fs-3 ms-3" title=@Resource.voltarTexto style="color:#6B97AC"></i></a>
</div>

<div class="w-50" style="margin-left:10%; margin-top:5%">
	<h3 style="display:inline;">@Resource.detalhesEncomendaViewTitle</h3>
	<a asp-action="Edit" asp-route-id="@Model?.Id" title=@Resource.modificarTexto><i class="ms-3 bi bi-pencil-fill"></i></a>
	<hr class="mb-5" />
	<dl class="row mt-4">
		<dt class="col-sm-4 mb-3">
			@Html.DisplayNameFor(model => model.Id)
		</dt>
		<dd class="col-sm-5 mb-3">
			@Html.DisplayFor(model => model.Id)
		</dd>
		<dt class="col-sm-4 mb-3">
			@Html.DisplayNameFor(model => model.IdLadoCliente)
		</dt>
		<dd class="col-sm-5 mb-3">
			@Html.DisplayFor(model => model.IdLadoCliente)
		</dd>
		<dt class="col-sm-4 mb-3">
			@Html.DisplayNameFor(model => model.ClienteId)
		</dt>
		<dd class="col-sm-5 mb-3">
			@Html.DisplayFor(model => model.Cliente.Nome)
		</dd>
		<dt class="col-sm-4 mb-3">
			@Html.DisplayNameFor(model => model.Data)
		</dt>
		<dd class="col-sm-5 mb-3">
			@Html.DisplayFor(model => model.Data)
		</dd>
		<dt class="col-sm-4 mb-3">
			@Html.DisplayNameFor(model => model.QuantidadeTotal)
		</dt>
		<dd class="col-sm-5 mb-3">
			@Html.DisplayFor(model => model.QuantidadeTotal)
		<dt class="col-sm-4 mb-3">
				@Html.DisplayNameFor(model => model.TotalPrecoUnit)
		</dt>
		<dd class="col-sm-5 mb-3">
				@Html.DisplayFor(model => model.TotalPrecoUnit)
		</dd>
		<dt class="col-sm-4 mb-3">
				@Html.DisplayNameFor(model => model.Transportadora)
		</dt>
		<dd class="col-sm-5 mb-3">
				@Html.DisplayFor(model => model.Transportadora)
		</dd>
		<dt class="col-sm-4 mb-3">
				@Html.DisplayNameFor(model => model.Estado)
		</dt>
		<dd class="col-sm-5 mb-3">
				@estadosEncomenda
		</dd>
	</dl>
</div>

Duil-App/Duil-App/Views/Encomendas/Index.cshtml
@model PaginatedList<Duil_App.Models.Encomendas>
@using Duil_App.Resources

@{
	ViewData["Title"] = Resource.Encomendas;
	ViewData["BodyClass"] = "paginas-index-fundo";
}
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css">
@if (TempData["SuccessMessage"] != null)
{
	<div class="alert alert-success" id="success-alert">
		@TempData["SuccessMessage"]
	</div>
}

<div class="container-fluid d-flex justify-content-center align-items-center position-relative"
	 style="height: 250px; background-color: #b4bdc1;">
	<h1 class="fw-light text-white">@Resource.Encomendas</h1>

	<a asp-action="Create"
	   class="btn position-absolute fs-5 px-5 py-3 navbar-blue text-white"
	   style="bottom: 0; transform: translateY(50%); right: 80px; border-radius: 10px;">
		@Resource.CriarEncomenda
	</a>
	<form asp-controller="Encomendas" asp-action="Index" method="get"
		  class="position-absolute fs-3 px-5 py-3 d-flex align-items-center"
		  style="bottom: 0; transform: translateY(50%); left: 100px; border-radius: 10px;">
		<input type="text" name="texto"
			   value="@Context.Request.Query["texto"]"
			   placeholder=@Resource.PesquisarCliente
			   class="form-control me-2"
			   style="min-width: 300px;" />

		<button type="submit" class="btn btn-light">
			<i class="bi bi-search"></i>
		</button>
	</form>
</div>
<div class="container p-5 mt-4">
	<table class="table table-hover">
		<thead>
			<tr>
				<th>
					@Resource.OrdemDeEncomenda
				</th>
				<th>
					@Html.DisplayNameFor(model => model[0].ClienteId)
				</th>
				<th>
					@Resource.NomeDoCliente
				</th>
				<th>
					@Html.DisplayNameFor(model => model[0].Data)
				</th>
				<th>
					@Html.DisplayNameFor(model => model[0].QuantidadeTotal)
				</th>
				<th>
					@Html.DisplayNameFor(model => model[0].TotalPrecoUnit)
				</th>
				<th>
					@Html.DisplayNameFor(model => model[0].Estado)
				</th>

				<th>
					@Resource.Acoes
				</th>
			</tr>
		</thead>
		<tbody>
			@foreach (var item in Model)
			{
				<tr>
					<td>
						@Html.DisplayFor(modelItem => item.IdLadoCliente)
					</td>
					<td>
						@Html.DisplayFor(modelItem => item.ClienteId)
					</td>
					<td>
						@Html.DisplayFor(modelItem => item.Cliente.Nome)
					</td>
					<td>
						@Html.DisplayFor(modelItem => item.Data)
					</td>
					<td>
						@Html.DisplayFor(modelItem => item.QuantidadeTotal)
					</td>
					<td>
						@Html.DisplayFor(modelItem => item.TotalPrecoUnit)
					</td>
					<td>
						@Html.DisplayFor(modelItem => item.Estado)
					</td>
					<td>
						<a asp-action="Details" asp-route-id="@item.Id"
						   class="btn btn-sm btn-outline-secondary"
						   title=@Resource.detalhesTexto>
							<i class="bi bi-info-circle-fill"></i>
						</a>
						@if (!User.IsInRole("Cliente"))
						{
							<a asp-action="Edit" asp-route-id="@item.Id"
							   class="btn btn-sm btn-outline-primary ms-1"
							   title=@Resource.modificarTexto>
								<i class="bi bi-pencil-fill"></i>
							</a>
							<a asp-action="Delete" asp-route-id="@item.Id"
							   class="btn btn-sm btn-outline-danger ms-1"
							   title=@Resource.Remover>
								<i class="bi bi-trash-fill"></i>
							</a>
						}
					</td>
				</tr>
			}
		</tbody>
	</table>
</div>
<script>
	setTimeout(function () {
		var alert = document.getElementById("success-alert");
		if (alert) {
			alert.style.transition = "opacity 0.5s ease-out";
			alert.style.opacity = "0";
			setTimeout(() => alert.remove(), 500); // remove da DOM após fade out
		}
	}, 3000); // 3 segundos
</script>


@{
	var prevDisabled = !Model.HasPreviousPage ? "disabled" : "";
	var nextDisabled = !Model.HasNextPage ? "disabled" : "";
}

<div class="d-flex justify-content-center gap-2 mt-4">
	<a asp-action="Index"
	   asp-route-sortOrder="@ViewData["CurrentSort"]"
	   asp-route-pageNumber="@(Model.PageIndex - 1)"
	   asp-route-currentFilter="@ViewData["CurrentFilter"]"
	   class="btn btn-secondary @prevDisabled">
		@Resource.Anterior
	</a>

	<a asp-action="Index"
	   asp-route-sortOrder="@ViewData["CurrentSort"]"
	   asp-route-pageNumber="@(Model.PageIndex + 1)"
	   asp-route-currentFilter="@ViewData["CurrentFilter"]"
	   class="btn btn-secondary @nextDisabled">
		@Resource.Seguinte
	</a>
</div>