Duil-App/Duil-App/Models/Fabricas.cs
using System.ComponentModel.DataAnnotations;
using Duil_App.Resources;

namespace Duil_App.Models
{
    /// <summary>
    /// Fábrica fornecedora de peças
    /// </summary>
    public class Fabricas : Empresas
    {

        /// <summary>
        /// Morada de descarga da fábrica
        /// </summary>
        [Display(Name = "MoradaDescarga", ResourceType = typeof(Resource))]
        [StringLength(100)]
        public string? MoradaDescarga { get; set; } 

        /// <summary>
        /// Peças que a fabrica produz
        /// </summary>
        public ICollection<Pecas>? Pecas { get; set; }
    }
}

Duil-App/Duil-App/Controllers/API/FabricasController.cs
using Duil_App.Data;
using Duil_App.Models;
using Duil_App.Models.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace Duil_App.Controllers.API
{
    [Authorize(Roles = "Admin,Funcionario")]
    [Route("api/[controller]")]
    [ApiController]
    public class FabricasController: ControllerBase
    {
        private readonly ApplicationDbContext _context;

        public FabricasController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: api/<FabricasController>
        /// <summary>
        /// Devolve uma lista com todas as Fabricas
        /// </summary>
        /// <returns></returns>
        [HttpGet]
        public async Task<ActionResult<IEnumerable<Fabricas>>> GetFabricas()
        {
            return await _context.Fabricas.ToListAsync();
        }

        // GET api/<FabricasController>/5
        /// <summary>
        /// Obtem uma Fabrica especifica
        /// </summary>
        /// <param name="nif">identificador da Fabrica</param>
        /// <returns>Fabrica com o ID passado</returns>
        [HttpGet("{nif}")]
        public async Task<ActionResult<Fabricas>> GetFabrica(string nif)
        {
            var fabrica = await _context.Fabricas.FindAsync(nif);

            if (fabrica == null)
            {
                return NotFound();
            }

            return fabrica;
        }


        // POST api/<FabricasController>
        /// <summary>
        /// Adiciona uma fabrica
        /// </summary>
        /// <param name="dto"></param>
        /// <returns></returns>
        [HttpPost]
        public async Task<ActionResult<Fabricas>> PostFabrica(FabricaDTO dto)
        {

            var novaFabrica = new Fabricas
            {
                Nif = dto.Nif,
                Nome = dto.Nome,
                Pais = dto.Pais,
                Morada = dto.Morada,
                CodPostal = dto.CodPostal,
                Telemovel = dto.Telemovel,
                Email = dto.Email,
                MoradaDescarga = dto.MoradaDescarga    
            };


            _context.Fabricas.Add(novaFabrica);
            await _context.SaveChangesAsync();

            return CreatedAtAction(nameof(GetFabrica),
                       new { id = novaFabrica.Nif },
                       novaFabrica);
        }


        // PUT api/<FabricasController>/5
        /// <summary>
        /// Modifica uma fabrica
        /// </summary>
        /// <param name="nif"></param>
        /// <param name="dto"></param>
        [HttpPut("{nif}")]
        public async Task<IActionResult> PutFabrica(string nif, FabricaDTO dto)
        {
            var fabrica = await _context.Fabricas.FindAsync(nif);

            if (fabrica == null)
            {
                return BadRequest();
            }

            // Atualizar apenas os campos permitidos
            fabrica.Nif = dto.Nif;
            fabrica.Nome = dto.Nome;
            fabrica.Pais = dto.Pais;
            fabrica.Morada = dto.Morada;
            fabrica.CodPostal = dto.CodPostal;
            fabrica.Telemovel = dto.Telemovel;
            fabrica.Email = dto.Email;
            fabrica.MoradaDescarga = dto.MoradaDescarga;

            _context.Entry(fabrica).State = EntityState.Modified;
            try
            {
                await _context.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                return StatusCode(500, "Erro de concorrência ao atualizar a fabrica.");
            }

            return NoContent();
        }

        // DELETE api/<FabricasController>/5
        /// <summary>
        /// Apaga uma fabrica
        /// </summary>
        /// <param name="nif"></param>
        [HttpDelete("{nif}")]
        public async Task<IActionResult> DeleteFabrica(string nif)
        {
            var fabrica = await _context.Fabricas.FindAsync(nif);
            if (fabrica == null)
            {
                return NotFound();
            }

            _context.Fabricas.Remove(fabrica);
            await _context.SaveChangesAsync();

            return NoContent();
        }
    }

}

Duil-App/Duil-App/Controllers/FabricasController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Duil_App.Data;
using Duil_App.Models;
using Microsoft.AspNetCore.Authorization;

namespace Duil_App.Controllers
{
    // Apenas acessível a Admin e Funcionário
    [Authorize(Roles = "Admin,Funcionario")]
    public class FabricasController : Controller
    {
        private readonly ApplicationDbContext _context;

        public FabricasController(ApplicationDbContext context)
        {
            _context = context;
        }

        // Listagem de fábricas
        public async Task<IActionResult> Index(string texto, int? pageNumber)
        {
            if (_context.Fabricas == null)
            {
                return Problem("Fabricas é um valor null.");
            }

            var fabricas = from c in _context.Fabricas
                           select c;

            // Aplicar filtro se houver texto de pesquisa
            if (!String.IsNullOrEmpty(texto))
            {
                fabricas = fabricas.Where(s => s.Nome!.ToUpper().Contains(texto.ToUpper()));
            }

            // Paginação com 10 resultados

            var pageSize = 10;
            return View(await PaginatedList<Fabricas>.CreateAsync(fabricas.AsNoTracking(), pageNumber ?? 1, pageSize));

        }

        // Retorna sugestões de nomes de fábricas para autocomplete
        [HttpGet]
        public IActionResult Search(string term)
        {
            var resultados = _context.Fabricas
                .Where(f => f.Nome.Contains(term))
                .Select(f => new {
                    label = f.Nome,
                    value = f.Nif
                })
                .Take(10)
                .ToList();

            return Json(resultados);
        }

        // Detalhes de um cliente especifico
        public async Task<IActionResult> Details(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var fabrica = await _context.Fabricas
                .FirstOrDefaultAsync(m => m.Nif == id);
            if (fabrica == null)
            {
                return NotFound();
            }

            return View(fabrica);
        }

        // Criação de fábricas
        public IActionResult Create()
        {
            return View();
        }

        // POST: Fabricas/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("MoradaDescarga,Nif,Nome,Morada,CodPostal,Pais,Telemovel,Email")] Fabricas fabrica)
        {
            // Validação de nif
            if (_context.Clientes.Any(c => c.Nif == fabrica.Nif))
            {
                ModelState.AddModelError("Nif", "Já existe uma fábrica ou cliente com este NIF.");
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Add(fabrica);
                    await _context.SaveChangesAsync();
                    return RedirectToAction(nameof(Index));
                }
                catch (DbUpdateException)
                {
                    ModelState.AddModelError("", "Ocorreu um erro ao guardar os dados. Nif inserido já existe");
                }
            }

            return View(fabrica);
        }

        // Formulário de edição de uma fábrica
        public async Task<IActionResult> Edit(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var fabrica = await _context.Fabricas.FindAsync(id);
            if (fabrica == null)
            {
                return NotFound();
            }
            return View(fabrica);
        }

        // Submissão do formulario de edição
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(string id, [Bind("MoradaDescarga,Nif,Nome,Morada,CodPostal,Pais,Telemovel,Email")] Fabricas fabrica)
        {
            if (id != fabrica.Nif)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(fabrica);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!FabricasExists(fabrica.Nif))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(fabrica);
        }

        // Confirmação da eliminação de uma fábrica
        public async Task<IActionResult> Delete(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var fabrica = await _context.Fabricas
                .FirstOrDefaultAsync(m => m.Nif == id);
            if (fabrica == null)
            {
                return NotFound();
            }

            return View(fabrica);
        }

        // Eliminação efetiva de uma fábrica
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(string id)
        {
            var fabrica = await _context.Fabricas.FindAsync(id);
            if (fabrica != null)
            {
                _context.Fabricas.Remove(fabrica);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool FabricasExists(string id)
        {
            return _context.Fabricas.Any(e => e.Nif == id);
        }
    }
}

Duil-App/Duil-App/Views/Fabricas/Create.cshtml
@model Duil_App.Models.Fabricas
@using Duil_App.Resources

@{
    ViewData["Title"] = Resource.adicionarFabricaViewTitle;
}

<div>
    <a asp-action="Index"><i class="bi bi-arrow-left fs-3 ms-3" style="color:#6B97AC"></i></a>
</div>

<div class="d-flex justify-content-center mt-5 min-vh-100">
    <div class="container mt-5" style="width:80%">
        <h3 class="mb-2 grey-text">@Resource.adicionarFabricaViewTitle</h3>
        <hr />

        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>

            <div class="row mt-5">
                <div class="col-md-5 me-5">
                    <div class="form-group mb-3">
                        <input asp-for="Nome" class="form-control" placeholder="@Resource.Nome *" />
                        <span asp-validation-for="Nome" class="text-danger"></span>
                    </div>
                    <div class="form-group mb-3">
                        <input asp-for="Nif" class="form-control" placeholder="@Resource.NIF *" />
                        <span asp-validation-for="Nif" class="text-danger"></span>
                    </div>
                    <div class="form-group mb-3">
                        <input asp-for="Email" class="form-control" placeholder="Email" />
                        <span asp-validation-for="Email" class="text-danger"></span>
                    </div>
                    <div class="form-group mb-3">
                        <input asp-for="Telemovel" class="form-control" placeholder=@Resource.Telemovel/>
                        <span asp-validation-for="Telemovel" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <input type="submit" value=@Resource.Adicionar class="btn btn-custom mt-3" />
                    </div>
                </div>

                <div class="col-md-5 ms-2">
                    <div class="form-group mb-3">
                        <input asp-for="Morada" class="form-control" placeholder=@Resource.Morada />
                        <span asp-validation-for="Morada" class="text-danger"></span>
                    </div>
                    <div class="form-group mb-3">
                        <input asp-for="MoradaDescarga" class="form-control" placeholder=@Resource.MoradaDescarga />
                        <span asp-validation-for="MoradaDescarga" class="text-danger"></span>
                    </div>
                    <div class="form-group mb-3">
                        <input class="form-control" value="Portugal" readonly />
                        <input type="hidden" name="Pais" value="Portugal" />
                    </div>
                    <div class="form-group mb-3">
                        <input asp-for="CodPostal" class="form-control" placeholder=@Resource.CodPostal />
                        <span asp-validation-for="CodPostal" class="text-danger"></span>
                    </div>
                    <p class="text-danger mt-4">@Resource.eDePreenchimentoObrigatorio</p>
                </div>
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

Duil-App/Duil-App/Views/Fabricas/Delete.cshtml
@model Duil_App.Models.Fabricas
@using Duil_App.Resources

@{
	ViewData["Title"] = Resource.ApagarFabricaViewTitle;
}
<div>
	<a asp-action="Index"><i class="bi bi-arrow-left fs-3 ms-3" tilte=@Resource.voltarTexto style="color:#6B97AC"></i></a>
</div>

<div class="w-50" style="margin-left:10%; margin-top:5%">
	<h3>@Resource.TemACertezaQueDesejaApagar @Resource.Fabrica?</h3>
	<div>
		<hr class="mb-5" />
		<dl class="row mt-4">
			<dt class="col-sm-4 mb-3">
				@Html.DisplayNameFor(model => model.Nif)
			</dt>
			<dd class="col-sm-5 mb-3">
				@Html.DisplayFor(model => model.Nif)
			</dd>
			<dt class="col-sm-4 mb-3">
				@Html.DisplayNameFor(model => model.Nome)
			</dt>
			<dd class="col-sm-5 mb-3">
				@(string.IsNullOrWhiteSpace(Model.Nome) ? Resource.semInfo: Model.Nome)
			</dd>
			<dt class="col-sm-4 mb-3">
				@Html.DisplayNameFor(model => model.Morada)
			</dt>
			<dd class="col-sm-5 mb-3">
				@(string.IsNullOrWhiteSpace(Model.Morada) ? Resource.semInfo : Model.Morada)
			</dd>
			<dt class="col-sm-4 mb-3">
				@Html.DisplayNameFor(model => model.MoradaDescarga)
			</dt>
			<dd class="col-sm-5 mb-3">
				@(string.IsNullOrWhiteSpace(Model.MoradaDescarga) ? Resource.semInfo : Model.MoradaDescarga)
			<dt class="col-sm-4 mb-3">
					@Html.DisplayNameFor(model => model.Pais)
			</dt>
			<dd class="col-sm-5 mb-3">
					@Html.DisplayFor(model => model.Pais)
			</dd>
			<dt class="col-sm-4 mb-3">
					@Html.DisplayNameFor(model => model.CodPostal)
			</dt>
			<dd class="col-sm-5 mb-3">
					@(string.IsNullOrWhiteSpace(Model.CodPostal) ? Resource.semInfo : Model.CodPostal)
			</dd>
			<dt class="col-sm-4 mb-3">
					@Html.DisplayNameFor(model => model.Telemovel)
			</dt>
			<dd class="col-sm-5 mb-3">
					@Html.DisplayFor(model => model.Telemovel)
			</dd>
			<dt class="col-sm-4 mb-3">
					@Html.DisplayNameFor(model => model.Email)
			</dt>
			<dd class="col-sm-5 mb-3">
					@(string.IsNullOrWhiteSpace(Model.Email) ? Resource.semInfo : Model.Email)
			</dd>
		</dl>
	</div>

	<form asp-action="Delete">
		<input type="hidden" asp-for="Nif" />
		<input type="submit" value=@Resource.Remover class="btn btn-danger" />
	</form>
</div>

Duil-App/Duil-App/Views/Fabricas/Details.cshtml
@model Duil_App.Models.Fabricas
@using Duil_App.Resources

@{
    ViewData["Title"] = Resource.DetalhesdaFabricaViewTitle;
}

<div>
    <a asp-action="Index"><i class="bi bi-arrow-left fs-3 ms-3" title=@Resource.voltarTexto style="color:#6B97AC"></i></a>
</div>

<div class="w-50" style="margin-left:10%; margin-top:5%">
    <h3 style="display:inline;"> @Resource.DetalhesdaFabricaViewTitle: @Model?.Nome </h3>
    <a asp-action="Edit" asp-route-id="@Model?.Nif" title=@Resource.modificarTexto><i class="ms-3 bi bi-pencil-fill"></i></a>
    <hr class="mb-5" />
    <dl class="row mt-4">
        <dt class="col-sm-4 mb-3">
            @Html.DisplayNameFor(model => model.Nif)
        </dt>
        <dd class="col-sm-5 mb-3">
            @Html.DisplayFor(model => model.Nif)
        </dd>
        <dt class="col-sm-4 mb-3">
            @Html.DisplayNameFor(model => model.Nome)
        </dt>
        <dd class="col-sm-5 mb-3">
            @(string.IsNullOrWhiteSpace(Model.Nome) ? Resource.semInfo : Model.Nome)
        </dd>
        <dt class="col-sm-4 mb-3">
            @Html.DisplayNameFor(model => model.Morada)
        </dt>
        <dd class="col-sm-5 mb-3">
            @(string.IsNullOrWhiteSpace(Model.Morada) ? Resource.semInfo : Model.Morada)
        </dd>
        <dt class="col-sm-4 mb-3">
            @Html.DisplayNameFor(model => model.MoradaDescarga)
        </dt>
        <dd class="col-sm-5 mb-3">
            @(string.IsNullOrWhiteSpace(Model.MoradaDescarga) ? Resource.semInfo : Model.MoradaDescarga)
        <dt class="col-sm-4 mb-3">
            @Html.DisplayNameFor(model => model.Pais)
        </dt>
        <dd class="col-sm-5 mb-3">
            @Html.DisplayFor(model => model.Pais)
        </dd>
            <dt class = "col-sm-4 mb-3">
            @Html.DisplayNameFor(model => model.CodPostal)
        </dt>
        <dd class = "col-sm-5 mb-3">
                @(string.IsNullOrWhiteSpace(Model.CodPostal) ? Resource.semInfo : Model.CodPostal)
        </dd>
        <dt class = "col-sm-4 mb-3">
            @Html.DisplayNameFor(model => model.Telemovel)
        </dt>
        <dd class = "col-sm-5 mb-3">
            @Html.DisplayFor(model => model.Telemovel)
        </dd>
        <dt class = "col-sm-4 mb-3">
            @Html.DisplayNameFor(model => model.Email)
        </dt>
        <dd class = "col-sm-5 mb-3">
                @(string.IsNullOrWhiteSpace(Model.Email) ? Resource.semInfo : Model.Email)
        </dd>
    </dl>
</div>

Duil-App/Duil-App/Views/Fabricas/Edit.cshtml
@model Duil_App.Models.Fabricas
@using Duil_App.Resources

@{
    ViewData["Title"] = Resource.ModificarFábricaVT;
}

<div>
    <a asp-action="Index"><i class="bi bi-arrow-left fs-3 ms-3" style="color:#6B97AC"></i></a>
</div>

<div class="d-flex justify-content-center mt-5 min-vh-100">
    <div class="container mt-5" style="width:80%">
        <h3 class="mb-2 grey-text">@Resource.ModificarFábricaVT: @Html.DisplayFor(Model => Model.Nome)</h3>
        <hr />
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="row mt-5">
                <div class="col-md-5 me-5">
                    <input asp-for="Nif" class="form-control mb-3" readonly />

                    <div class="form-group mb-3">
                        <input asp-for="Nome" class="form-control" placeholder="@Resource.Nome *" />
                        <span asp-validation-for="Nome" class="text-danger"></span>
                    </div>

                    <div class="form-group mb-3">
                        <input asp-for="Email" class="form-control" placeholder="Email" />
                        <span asp-validation-for="Email" class="text-danger"></span>
                    </div>

                    <div class="form-group mb-3">
                        <input asp-for="Telemovel" class="form-control" placeholder=@Resource.Telemovel />
                        <span asp-validation-for="Telemovel" class="text-danger"></span>
                    </div>

                    <div class="form-group mb-3">
                        <input type="submit" value=@Resource.GuardarAlteracoes class="btn btn-custom mt-3" />
                    </div>
                </div>

                <div class="col-md-5 ms-2">
                    <div class="form-group mb-3">
                        <input asp-for="Morada" class="form-control" placeholder=@Resource.Morada />
                        <span asp-validation-for="Morada" class="text-danger"></span>
                    </div>

                    <div class="form-group mb-3">
                        <input asp-for="CodPostal" class="form-control" placeholder=@Resource.CodPostal />
                        <span asp-validation-for="CodPostal" class="text-danger"></span>
                    </div>

                    <div class="form-group mb-3">
                        <input asp-for="MoradaDescarga" class="form-control" placeholder=@Resource.MoradaDescarga />
                        <span asp-validation-for="MoradaDescarga" class="text-danger"></span>
                    </div>

                    <input asp-for="Pais" class="form-control" readonly />
                    <p class="text-danger mt-4">@Resource.eDePreenchimentoObrigatorio</p>
                </div>
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

Duil-App/Duil-App/Views/Fabricas/Index.cshtml
@model PaginatedList<Duil_App.Models.Fabricas>
@using Duil_App.Resources

@{
    ViewData["Title"] = Resource.Fabricas;
    ViewData["BodyClass"] = "paginas-index-fundo";
}
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css">


<div class="container-fluid d-flex justify-content-center align-items-center position-relative"
     style="height: 250px; background-color: #b4bdc1;">
    <h1 class="fw-light text-white">@Resource.Fabricas</h1>

    <a asp-action="Create"
       class="btn position-absolute fs-5 px-5 py-3 navbar-blue text-white"
       style="bottom: 0; transform: translateY(50%); right: 80px; border-radius: 10px;">
        @Resource.adicionarFabrica
    </a>
    <form asp-controller="Fabricas" asp-action="Index" method="get"
          class="position-absolute fs-3 px-5 py-3 d-flex align-items-center"
          style="bottom: 0; transform: translateY(50%); left: 100px; border-radius: 10px;">
        <input type="text" name="texto"
               value="@Context.Request.Query["texto"]"
               placeholder=@Resource.PesquisarPorNome
               class="form-control me-2"
               style="min-width: 300px;" />

        <button type="submit" class="btn btn-light">
            <i class="bi bi-search"></i>
        </button>
    </form>

</div>
<div class="container p-5 mt-4">
    <table class="table table-hover">
        <thead>
            <tr>
                <th>@Html.DisplayNameFor(model => model[0].Nif)</th>
                <th>@Html.DisplayNameFor(model => model[0].Nome)</th>
                <th>@Html.DisplayNameFor(model => model[0].Pais)</th>
                <th>@Html.DisplayNameFor(model => model[0].Telemovel)</th>
                <th>@Resource.Acoes</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>@Html.DisplayFor(modelItem => item.Nif)</td>
                    <td>@Html.DisplayFor(modelItem => item.Nome)</td>
                    <td>@Html.DisplayFor(modelItem => item.Pais)</td>
                    <td>@Html.DisplayFor(modelItem => item.Telemovel)</td>
                    <td>
                        <a asp-action="Details" asp-route-id="@item.Nif"
                           class="btn btn-sm btn-outline-secondary"
                           title=@Resource.DetalhesDe>
                            <i class="bi bi-info-circle-fill"></i>
                        </a>
                        <a asp-action="Edit" asp-route-id="@item.Nif"
                           class="btn btn-sm btn-outline-primary ms-1"
                           title=@Resource.modificarTexto>
                            <i class="bi bi-pencil-fill"></i>
                        </a>
                        <a asp-action="Delete" asp-route-id="@item.Nif"
                           class="btn btn-sm btn-outline-danger ms-1"
                           title=@Resource.Remover>
                            <i class="bi bi-trash-fill"></i>
                        </a>

                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>

@{
    var prevDisabled = !Model.HasPreviousPage ? "disabled" : "";
    var nextDisabled = !Model.HasNextPage ? "disabled" : "";
}

<div class="d-flex justify-content-center gap-2 mt-4">
    <a asp-action="Index"
       asp-route-sortOrder="@ViewData["CurrentSort"]"
       asp-route-pageNumber="@(Model.PageIndex - 1)"
       asp-route-currentFilter="@ViewData["CurrentFilter"]"
       class="btn btn-secondary @prevDisabled">
        @Resource.Anterior
    </a>

    <a asp-action="Index"
       asp-route-sortOrder="@ViewData["CurrentSort"]"
       asp-route-pageNumber="@(Model.PageIndex + 1)"
       asp-route-currentFilter="@ViewData["CurrentFilter"]"
       class="btn btn-secondary @nextDisabled">
        @Resource.Seguinte
    </a>
</div>