Duil-App/Duil-App/Models/Clientes.cs
using System.ComponentModel.DataAnnotations;
using Duil_App.Resources;

namespace Duil_App.Models
{
    /// <summary>
    /// Empresa que realiza a encomenda
    /// </summary>
    public class Clientes : Empresas
    {

		/// <summary>
		/// Morada de carga da empresa cliente
		/// </summary>
		[Display(Name = "MoradaCarga", ResourceType = typeof(Resource))]

		[StringLength(255)]
        public string? MoradaCarga { get; set; }

        /// <summary>
        /// Lista de encomendas efetuadas pela empresa cliente
        /// </summary>
        public ICollection<Encomendas>? Encomendas { get; set; }
    }
}

Duil-App/Duil-App/Controllers/API/ClientesController.cs
using Duil_App.Data;
using Duil_App.Models;
using Duil_App.Models.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace Duil_App.Controllers.API
{
    [Authorize(Roles = "Admin,Funcionario")]
    [Route("api/[controller]")]
    [ApiController]
    public class ClientesController : ControllerBase
    {
        private readonly ApplicationDbContext _context;

        public ClientesController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: api/<ClientesController>
        /// <summary>
        /// Devolve uma lista com todas as Clientes
        /// </summary>
        /// <returns></returns>
        [HttpGet]
        public async Task<ActionResult<IEnumerable<Clientes>>> GetClientes()
        {
            return await _context.Clientes.ToListAsync();
        }

        // GET api/<ClientesController>/5
        /// <summary>
        /// Obtem um Cliente especifico
        /// </summary>
        /// <param name="nif">identificador de Cliente</param>
        /// <returns>Cliente com o ID passado</returns>
        [HttpGet("{nif}")]
        public async Task<ActionResult<Clientes>> GetCliente(string nif)
        {
            var cliente = await _context.Clientes.FindAsync(nif);

            if (cliente == null)
            {
                return NotFound();
            }

            return cliente;
        }


        // POST api/<ClientesController>
        /// <summary>
        /// Adiciona um cliente
        /// </summary>
        /// <param name="dto"></param>
        /// <returns></returns>
        [HttpPost]
        public async Task<ActionResult<Clientes>> PostCliente(ClienteDTO dto)
        {

            var novoCliente = new Clientes
            {
                Nif = dto.Nif,
                Nome = dto.Nome,
                Pais = dto.Pais,
                Morada = dto.Morada,
                CodPostal = dto.CodPostal,
                Telemovel = dto.Telemovel,
                Email = dto.Email,
                MoradaCarga = dto.MoradaCarga
            };


            _context.Clientes.Add(novoCliente);
            await _context.SaveChangesAsync();

            return CreatedAtAction(nameof(GetCliente),
                       new { id = novoCliente.Nif },
                       novoCliente);
        }


        // PUT api/<ClientesController>/5
        /// <summary>
        /// Modifica um Cliente
        /// </summary>
        /// <param name="nif"></param>
        /// <param name="dto"></param>
        [HttpPut("{nif}")]
        public async Task<IActionResult> PutCliente(string nif, ClienteDTO dto)
        {
            var cliente = await _context.Clientes.FindAsync(nif);

            if (cliente == null)
            {
                return BadRequest();
            }

            // Atualizar apenas os campos permitidos
            cliente.Nif = dto.Nif;
            cliente.Nome = dto.Nome;
            cliente.Pais = dto.Pais;
            cliente.Morada = dto.Morada;
            cliente.CodPostal = dto.CodPostal;
            cliente.Telemovel = dto.Telemovel;
            cliente.Email = dto.Email;
            cliente.MoradaCarga = dto.MoradaCarga;

            _context.Entry(cliente).State = EntityState.Modified;
            try
            {
                await _context.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                return StatusCode(500, "Erro de concorrência ao atualizar a cliente.");
            }

            return NoContent();
        }

        // DELETE api/<ClientesController>/5
        /// <summary>
        /// Apaga um cliente
        /// </summary>
        /// <param name="nif"></param>
        [HttpDelete("{nif}")]
        public async Task<IActionResult> DeleteCliente(string nif)
        {
            var cliente = await _context.Clientes.FindAsync(nif);
            if (cliente == null)
            {
                return NotFound();
            }

            _context.Clientes.Remove(cliente);
            await _context.SaveChangesAsync();

            return NoContent();
        }
    }

}

Duil-App/Duil-App/Controllers/ClientesController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Duil_App.Data;
using Duil_App.Models;
using Microsoft.AspNetCore.Authorization;
using Duil_App.Code;

namespace Duil_App.Controllers
{
    public class ClientesController : Controller
    {
        private readonly ApplicationDbContext _context;

        // Método auxiliar para obter lista de páises 
        private List<SelectListItem> ObterPaises()
        {
            return ListasHelper.ObterListaDePaises();
        }

        public ClientesController(ApplicationDbContext context)
        {
            _context = context;
        }

        // Listagem de clientes apenas acessível para Admin e Funcionário
        [Authorize(Roles = "Admin, Funcionario")]
        public async Task<IActionResult> Index(string texto, int? pageNumber)
        {
            if (_context.Clientes == null)
            {
                return Problem("Clientes é um valor null.");
            }

            // Aplicar filtro se houver texto de pesquisa
            var clientes = from c in _context.Clientes
                           select c;

            if (!String.IsNullOrEmpty(texto))
            {
                clientes = clientes.Where(s => s.Nome!.ToUpper().Contains(texto.ToUpper()));
            }

            // Paginação com 10 resultados
            int pageSize = 10;
            return View(await PaginatedList<Clientes>.CreateAsync(clientes.AsNoTracking(), pageNumber ?? 1, pageSize));

        }

        // Retorna sugestões de nomes de clientes para autocomplete
        [HttpGet]
        public IActionResult Search(string term)
        {
            var resultados = _context.Clientes
                .Where(c => c.Nome.Contains(term))
                .Select(c => new
                {
                    label = c.Nome,
                    value = c.Nif
                })
                .Take(10)
                .ToList();

            return Json(resultados);
        }

        // Detalhes de um cliente 
        public async Task<IActionResult> Details(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var cliente = await _context.Clientes
                .FirstOrDefaultAsync(m => m.Nif == id);
            if (cliente == null)
            {
                return NotFound();
            }

            ViewBag.Pais = ObterPaises();
            return View(cliente);
        }

        // Criação de cliente
        [Authorize(Roles = "Admin")]
  
        public IActionResult Create()
        {
            ViewBag.Pais = ObterPaises();
            return View();
        }

        [Authorize(Roles = "Admin")]

        // Submissão do formulário de criação
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("MoradaCarga,Nif,Nome,Morada,CodPostal,Pais,Telemovel,Email")] Clientes cliente)
        {
            // Validação de nif
            if (_context.Clientes.Any(c => c.Nif == cliente.Nif))
            {
                ModelState.AddModelError("Nif", "Já existe um cliente com este NIF.");
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Add(cliente);
                    await _context.SaveChangesAsync();
                    return RedirectToAction(nameof(Index));
                }
                catch (DbUpdateException)
                {
                    ModelState.AddModelError("", "Ocorreu um erro ao guardar os dados. Nif inserido já existe");
                }
            }

            ViewBag.Pais = ObterPaises();
            return View(cliente);

        }

        // Formulário de edição de um cliente
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Edit(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var cliente = await _context.Clientes.FindAsync(id);
            if (cliente == null)
            {
                return NotFound();
            }
            ViewBag.Pais = ObterPaises();
            return View(cliente);
        }

        // Submissão do formulario de edição
        [Authorize(Roles = "Admin")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(string id, [Bind("MoradaCarga,Nif,Nome,Morada,CodPostal,Pais,Telemovel,Email")] Clientes cliente)
        {
            ViewBag.Pais = ObterPaises();
            if (id != cliente.Nif)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(cliente);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ClientesExists(cliente.Nif))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }

            ViewBag.Pais = ObterPaises();
            return View(cliente);
        }

        // Confirmação da eliminação de um cliente
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Delete(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var cliente = await _context.Clientes
                .FirstOrDefaultAsync(m => m.Nif == id);
            if (cliente == null)
            {
                return NotFound();
            }

            return View(cliente);
        }


        [Authorize(Roles = "Admin")]
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(string id)
        {
            var cliente = await _context.Clientes.FindAsync(id);
            if (cliente != null)
            {
                _context.Clientes.Remove(cliente);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ClientesExists(string id)
        {
            return _context.Clientes.Any(e => e.Nif == id);
        }


    }


}

Duil-App/Duil-App/Views/Clientes/Create.cshtml
@model Duil_App.Models.Clientes
@using Duil_App.Resources

@{
	ViewData["Title"] = Resource.ClienteCreateViewTitle;
}

<div>
	<a asp-action="Index"><i class="bi bi-arrow-left fs-3 ms-3" style="color:#6B97AC"></i></a>
</div>

<div class="d-flex justify-content-center mt-5 min-vh-100">
	<div class="container mt-5" style="width:80%">
		<h3 class="mb-2 grey-text">@Resource.ClienteCreateTitle</h3>
		<hr />

		<form asp-action="Create">
			<div asp-validation-summary="ModelOnly" class="text-danger"></div>

			<div class="row mt-5">
				<div class="col-md-5 me-5">
					<div class="form-group mb-3">
						<input asp-for="Nome" class="form-control" placeholder="@Resource.Nome *" />
						<span asp-validation-for="Nome" class="text-danger"></span>
					</div>
					<div class="form-group mb-3">
						<input asp-for="Nif" class="form-control" placeholder="@Resource.NIF *" />
						<span asp-validation-for="Nif" class="text-danger"></span>
					</div>
					<div class="form-group mb-3">
						<input asp-for="Email" class="form-control" placeholder="Email" />
						<span asp-validation-for="Email" class="text-danger"></span>
					</div>
					<div class="form-group mb-3">
						<input asp-for="Telemovel" class="form-control" placeholder="@Resource.Telemovel" />
						<span asp-validation-for="Telemovel" class="text-danger"></span>
					</div>
					<div class="form-group ">
						<input type="submit" value="@Resource.Criar" class="btn btn-custom mt-3" />
					</div>
				</div>

				<div class="col-md-5 ms-2">
					<div class="form-group mb-3">
						<input asp-for="Morada" class="form-control" placeholder="@Resource.Morada" />
						<span asp-validation-for="Morada" class="text-danger"></span>
					</div>
					<div class="form-group mb-3">
						<input asp-for="CodPostal" class="form-control" placeholder="@Resource.CodPostal" />
						<span asp-validation-for="CodPostal" class="text-danger"></span>
					</div>
					<div class="form-group mb-3 ">
						<input asp-for="MoradaCarga" class="form-control" placeholder="@Resource.MoradaCarga" />
						<span asp-validation-for="MoradaCarga" class="text-danger"></span>
					</div>
					<div class="form-group mb-3">
						<select asp-for="Pais" class="form-control" asp-items="ViewBag.Pais">
							<option value="">@Resource.SelecionarPais *</option>
						</select>
						<span asp-validation-for="Pais" class="text-danger"></span>
					</div>
					<p class="text-danger mt-4">* @Resource.eDePreenchimentoObrigatorio</p>
				</div>
			</div>
		</form>
	</div>
</div>


@section Scripts {
	@{
		await Html.RenderPartialAsync("_ValidationScriptsPartial");
	}
}

Duil-App/Duil-App/Views/Clientes/Delete.cshtml
@model Duil_App.Models.Clientes
@using Duil_App.Resources

@{
	ViewData["Title"] = Resource.Remover + " " + Resource.Cliente;
}


<div>
	<a asp-action="Index"><i class="bi bi-arrow-left fs-3 ms-3" title="@Resource.voltarTexto" style="color:#6B97AC"></i></a>
</div>


<div class="w-50" style="margin-left:10%; margin-top:5%">
	<h3>@Resource.TemACertezaQueDesejaApagar @Resource.esteHelper @Resource.Cliente?</h3>
	<div>
		<hr class="mb-5" />
		<dl class="row mt-4">
			<dt class="col-sm-4 mb-3">
				@Html.DisplayNameFor(model => model.Nif)
			</dt>
			<dd class="col-sm-5 mb-3">
				@Html.DisplayFor(model => model.Nif)
			</dd>
			<dt class="col-sm-4 mb-3">
				@Html.DisplayNameFor(model => model.Nome)
			</dt>
			<dd class="col-sm-5 mb-3">
				@(string.IsNullOrWhiteSpace(Model.Nome) ? Resource.semInfo : Model.Nome)
			</dd>
			<dt class="col-sm-4 mb-3">
				@Html.DisplayNameFor(model => model.Morada)
			</dt>
			<dd class="col-sm-5 mb-3">
				@(string.IsNullOrWhiteSpace(Model.Morada) ? Resource.semInfo : Model.Morada)
			</dd>
			<dt class="col-sm-4 mb-3">
				@Html.DisplayNameFor(model => model.MoradaCarga)
			</dt>
			<dd class="col-sm-5 mb-3">
				@(string.IsNullOrWhiteSpace(Model.MoradaCarga) ? Resource.semInfo : Model.MoradaCarga)
			</dd>
			<dt class="col-sm-4 mb-3">
				@Html.DisplayNameFor(model => model.Pais)
			</dt>
			<dd class="col-sm-5 mb-3">
				@Html.DisplayFor(model => model.Pais)
			</dd>
			<dt class="col-sm-4 mb-3">
				@Html.DisplayNameFor(model => model.CodPostal)
			</dt>
			<dd class="col-sm-5 mb-3">
				@(string.IsNullOrWhiteSpace(Model.CodPostal) ? Resource.semInfo : Model.CodPostal)
			</dd>
			<dt class="col-sm-4 mb-3">
				@Html.DisplayNameFor(model => model.Telemovel)
			</dt>
			<dd class="col-sm-5 mb-3">
				@(string.IsNullOrWhiteSpace(Model.CodPostal) ? Resource.semInfo : Model.Telemovel)
			</dd>
			<dt class="col-sm-4 mb-3">
				@Html.DisplayNameFor(Model => Model.Email)
			</dt>
			<dd class="col-sm-5 mb-3">
				@(string.IsNullOrWhiteSpace(Model.Email) ? Resource.semInfo : Model.Email)
			</dd>

		</dl>
	</div>

	<form asp-action="Delete">
		<input type="hidden" asp-for="Nif" />
		<input type="submit" value="@Resource.Remover" class="btn btn-danger" />
	</form>
</div>

Duil-App/Duil-App/Views/Clientes/Details.cshtml
@model Duil_App.Models.Clientes
@using Duil_App.Resources

@{
    ViewData["Title"] = Resource.detalhesDeAlgo + " " + Resource.Cliente;
}

<div>
    <a asp-action="Index"><i class="bi bi-arrow-left fs-3 ms-3" title=@Resource.voltarTexto style="color:#6B97AC"></i></a>
</div>


<div class="w-50" style="margin-left:10%; margin-top:5%">
    <h3 style="display:inline;">@Html.DisplayFor(model => model.Nome)</h3>
    <a asp-action="Edit" asp-route-id="@Model?.Nif" title=@Resource.modificarTexto><i class="ms-3 bi bi-pencil-fill"></i></a>
    <hr class="mb-5" />
    <dl class="row mt-4">
        <dt class="col-sm-4 mb-3">
            @Html.DisplayNameFor(model => model.Nif)
        </dt>
        <dd class="col-sm-5 mb-3">
            @Html.DisplayFor(model => model.Nif)
        </dd>
        <dt class = "col-sm-4 mb-3">
            @Html.DisplayNameFor(model => model.Nome)
        </dt>
        <dd class = "col-sm-5 mb-3">
            @(string.IsNullOrWhiteSpace(Model.Nome) ? Resource.semInfo : Model.Nome)
        </dd>
        <dt class = "col-sm-4 mb-3">
            @Html.DisplayNameFor(model => model.Morada)
        </dt>
        <dd class = "col-sm-5 mb-3">
            @(string.IsNullOrWhiteSpace(Model.Morada) ? Resource.semInfo : Model.Morada)
        </dd>
        <dt class="col-sm-4 mb-3">
            @Html.DisplayNameFor(model => model.MoradaCarga)
        </dt>
        <dd class="col-sm-5 mb-3">
            @(string.IsNullOrWhiteSpace(Model.MoradaCarga) ? Resource.semInfo : Model.MoradaCarga)
        </dd>
        <dt class="col-sm-4 mb-3">
            @Html.DisplayNameFor(model => model.Pais)
        </dt>
        <dd class="col-sm-5 mb-3">
            @Html.DisplayFor(model => model.Pais)
        </dd>
        <dt class = "col-sm-4 mb-3">
            @Html.DisplayNameFor(model => model.CodPostal)
        </dt>
        <dd class = "col-sm-5 mb-3">
            @(string.IsNullOrWhiteSpace(Model.CodPostal) ? Resource.semInfo : Model.CodPostal)
        </dd>
        <dt class = "col-sm-4 mb-3">
            @Html.DisplayNameFor(model => model.Telemovel)
        </dt>
        <dd class = "col-sm-5 mb-3">
            @(string.IsNullOrWhiteSpace(Model.CodPostal) ? Resource.semInfo : Model.Telemovel)
        </dd>
        <dt class = "col-sm-4 mb-3">
            @Html.DisplayNameFor(Model => Model.Email)
        </dt>
        <dd class="col-sm-5 mb-3">
            @(string.IsNullOrWhiteSpace(Model.Email) ? Resource.semInfo : Model.Email)
        </dd>
        
    </dl>
</div>
<div>
   
</div>

Duil-App/Duil-App/Views/Clientes/Edit.cshtml
@model Duil_App.Models.Clientes
@using Duil_App.Resources

@{
	ViewData["Title"] = Resource.modificarTexto + " " + Resource.Cliente;
}

<div>
	<a asp-action="Index"><i class="bi bi-arrow-left fs-3 ms-3" tilte=@Resource.voltarTexto style="color:#6B97AC"></i></a>
</div>

<div class="d-flex justify-content-center mt-5 min-vh-100">
	<div class="container mt-5" style="width:80%">
		<h3 class="mb-2 grey-text">@Resource.modificarTexto @Html.DisplayFor(Model => Model.Nome)</h3>
		<hr />
		<form asp-action="Edit">
			<div asp-validation-summary="ModelOnly" class="text-danger"></div>
			<div class="row mt-5">
				<div class="col-md-5 me-5">
					<div class="form-group mb-3">
						<input asp-for="Nome" class="form-control" placeholder="@Resource.Nome *" />
						<span asp-validation-for="Nome" class="text-danger"></span>
					</div>
					<input asp-for="Nif" class="form-control mb-3" readonly />
					<div class="form-group mb-3">
						<input asp-for="Email" class="form-control" placeholder="Email" />
						<span asp-validation-for="Email" class="text-danger"></span>
					</div>
					<div class="form-group mb-3">
						<input asp-for="Telemovel" class="form-control" placeholder="@Resource.Telemovel" />
						<span asp-validation-for="Telemovel" class="text-danger"></span>
					</div>
					<div class="form-group mb-3">
						<input type="submit" value=@Resource.GuardarAlteracoes class="btn btn-custom mt-3" />
					</div>
				</div>

				<div class="col-md-5 ms-2">
					<div class="form-group mb-3">
						<input asp-for="Morada" class="form-control" placeholder=@Resource.Morada />
						<span asp-validation-for="Morada" class="text-danger"></span>
					</div>
					<div class="form-group mb-3">
						<input asp-for="CodPostal" class="form-control" placeholder=@Resource.CodPostal />
						<span asp-validation-for="CodPostal" class="text-danger"></span>
					</div>
					<div class="form-group mb-3">
						<input asp-for="MoradaCarga" class="form-control" placeholder=@Resource.MoradaCarga />
						<span asp-validation-for="MoradaCarga" class="text-danger"></span>
					</div>
					<div asp-validation-summary="ModelOnly" class="text-danger"></div>
					<input asp-for="Pais" class="form-control" readonly />
					<p class="text-danger mt-4">* @Resource.eDePreenchimentoObrigatorio</p>
				</div>
			</div>
		</form>
	</div>
</div>


@section Scripts {
	@{
		await Html.RenderPartialAsync("_ValidationScriptsPartial");
	}
}

Duil-App/Duil-App/Views/Clientes/Index.cshtml
@model PaginatedList<Duil_App.Models.Clientes>
@using Duil_App.Resources

@{
    ViewData["Title"] = Resource.IndexClientes;
    ViewData["BodyClass"] = "paginas-index-fundo";
}
<div class="container-fluid d-flex justify-content-center align-items-center position-relative" More actions
     style="height: 250px; background-color: #b4bdc1;">

    <h1 class="fw-light text-white">Clientes</h1>

    <a asp-action="Create"
       class="btn position-absolute fs-5 px-5 py-3 navbar-blue text-white"
       style="bottom: 0; transform: translateY(50%); right: 80px; border-radius: 10px;">
        Adicionar Cliente
    </a>

    <form asp-controller="Clientes" asp-action="Index" method="get"
          class="position-absolute fs-3 px-5 py-3 d-flex align-items-center"
          style="bottom: 0; transform: translateY(50%); left: 100px; border-radius: 10px;">
        <input type="text" name="texto"
               value="@Context.Request.Query["texto"]"
               placeholder=@Resource.PesquisarPorNome
               class="form-control me-2"
               style="min-width: 300px;" />

        <button type="submit" class="btn btn-light">
            <i class="bi bi-search"></i>
        </button>
    </form>
</div>

<div class="container p-5 mt-4">
    <table class="table table-hover">
        <thead>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model[0].Nif)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model[0].Nome)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model[0].Pais)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model[0].Telemovel)
                </th>
                <th>
                    @Resource.Acoes
                </th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Nif)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Nome)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Pais)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Telemovel)
                    </td>
                    <td>
                        <a asp-action="Details" asp-route-id="@item.Nif"
                           class="btn btn-sm btn-outline-secondary"
                           title=@Resource.detalhesTexto>
                            <i class="bi bi-info-circle-fill"></i>
                        </a>
                        @if (User.IsInRole("Admin"))
                        {
                            <a asp-action="Edit" asp-route-id="@item.Nif"
                               class="btn btn-sm btn-outline-primary ms-1"
                               title=@Resource.modificarTexto>
                                <i class="bi bi-pencil-fill"></i>
                            </a>
                            <a asp-action="Delete" asp-route-id="@item.Nif"
                               class="btn btn-sm btn-outline-danger ms-1"
                               title=@Resource.Remover>
                                <i class="bi bi-trash-fill"></i>
                            </a>
                        }
                    </td>
                </tr>
            }
        </tbody>
    </table>


</div>


@{
    var prevDisabled = !Model.HasPreviousPage ? "disabled" : "";
    var nextDisabled = !Model.HasNextPage ? "disabled" : "";
}

<div class="d-flex justify-content-center gap-2 mt-4">
    <a asp-action="Index"
       asp-route-sortOrder="@ViewData["CurrentSort"]"
       asp-route-pageNumber="@(Model.PageIndex - 1)"
       asp-route-currentFilter="@ViewData["CurrentFilter"]"
       class="btn btn-secondary @prevDisabled">
        @Resource.Anterior
    </a>

    <a asp-action="Index"
       asp-route-sortOrder="@ViewData["CurrentSort"]"
       asp-route-pageNumber="@(Model.PageIndex + 1)"
       asp-route-currentFilter="@ViewData["CurrentFilter"]"
       class="btn btn-secondary @nextDisabled">
        @Resource.Seguinte
    </a>
</div>